Add button to toggle between dark/light mode
theramis/aucvid pull request #57
Opened 2021-10-29 23:11 UTC by jishaal

@finnclark this is what I was thinking for the dark mode toggle btn. Feedback would be primo. 

Lets hope the preview builds 😅

2021-10-29 23:18 UTC, finnclark commented
Hey mate, appreciate the effort but if it's ok, I would be keen to think about this more... Icon toggle buttons aren't a great UX pattern as there's confusion between whether the icon represents the state it's in vs what typically a button does which is describe the action it takes

2021-10-29 23:21 UTC, jishaal commented
Sure thing @finnclark 👍🏼

2021-10-29 23:32 UTC, finnclark requested changes
Suggestion to increase the touch target to 40px.

another ask - could we see what it's like with the icons swapped so the icon represents the action rather than the state?

2021-10-29 23:32 UTC, finnclark commented on app/components/DarkModeToggle/DarkModeToggle.module.scss
> +  height: 1.25rem;
```suggestion
  width: 2.5rem;
  height: 2.5rem;
  padding: .625rem;
```

2021-10-30 00:03 UTC, finnclark approved these changes
LGTM for now! Might look at something a little different with new design... I'm personally more a fan of a control that's a bit clearer. But this is a great thing to provide value incrementally. Perfection is the enemy of done or something?

2021-10-30 00:06 UTC, andycarrell approved these changes

2021-10-30 00:14 UTC, merged

2021-10-30 00:14 UTC, jishaal commented
Thanks @finnclark , fair enough definitely understand this isn't ideal => we can move to the toggle switch or something more clearer once you've had a chance to explore